### PR TITLE
E-mail verification support

### PR DESCRIPTION
**Pull request by vsimonian**
**This PR is not feature-complete at time of submission. Commits will be added.**

At the time of this PR being created:

- Added support for e-mails and e-mail templating using consolidate
- Added initial support for e-mail verification (_is not enforced yet_)
- Updated branding to reflect new Anvil logo and style

### CODE REVIEW

**Comment by Cynfusion** [comment]
@vsimonian does this include any written messaging directly to the user?

**Comment by christiansmith** [comment]
@Cynfusion yes, it presents at least two messages to the user. I think we should demo this and do a code/UX review at the hangout this week. 

@vsimonian are you able to make it this Thursday?

**Comment by Cynfusion** [comment]
Ya, I'd totally like to help with user messaging stuff; we'd be way ahead of the game to get those looking good early on

**Comment by christiansmith** [comment]
@Cynfusion if you're up for it, I'm sure we could use some help with documenting this feature as well

**Comment by vsimonian** [comment]
@christiansmith I don't foresee any problems getting to this Thursday's hangout.

@Cynfusion Here's what the user sees:

E-mail message

Verification page

Later (and shortly) there will also need to be a page that informs the user to check their e-mail for a verification request.

**Comment by vsimonian** [comment]
Some flows we cooked up @christiansmith 

img_20150720_225158

**Comment by adi-ads** [comment]
User Flow 

When user tries to sign-in and email is not verified user is prompted to check their email to verify their email account with an optional link to re-send the email.

**Comment by adi-ads** [comment]
Token Verification ->

If the user email is already verified and the user clicks on a verification link (latest or old) the user is prompted with "email already verified" message.

If user email is not verified and verification token is not valid then only the user gets the not valid token message

**Comment by christiansmith** [comment]
Excellent work @vsimonian! Thank you!

**Pull request merged**
