### PR TITLE
Two issues found while looking at issue #74

### PR DESCRIPTION
**Pull request by JiCiT**
Corrected the modina require issue as discussed in #74 plus, while looking into that, I found that the wrong directory was being searched for custom protocols.

### CODE REVIEW

**Comment by christiansmith** [comment]
Sorry, @JiCiT. This is actually looking where we want it to. The feature is experimental and as yet undocumented. It allows you to create custom passport strategies (not npm modules) in a `protocols` directory within your deployment repository. There are still some issues to iron out. It should throw an error only if you configure a provider that has no corresponding protocol/strategy that's built into Anvil or defined specific to your project. There is a bug on some platforms that seems to trace back to the `ursa` module. @tomkersten and I are looking into it.

If you have further thoughts on how loading custom protocols ought to work, we'd love to hear them.

**Comment by JiCiT** [comment]
This is just off the top of my head, so take it for what it's worth.  You've probably already thought about this.

The reason I thought it was looking in the wrong place was because it was initially searching in, in my case, /usr/local/lib/node_modules/anvil-connect/protocols/OAuth2.  It found it and tried to require but erred out due to the Modina vs. modina issue.  The code essentially ignores any issues at that point by capturing any exception and then not doing anything with it.  I assume the idea being that there's an assumption being made that any issue at that point is because the .js file will be found in the next section looking for a custom provider.

Any issue encountered in the first part should be reported, especially if the error was anything other than not being able to find the file to require.  If it is not being able to find the file, then at least a warning about not being able to find it and that an attempt will be made to find a custom provider.  Better still would be to have some way of knowing whether the provider being searched for is built-in or custom upfront and only searching in the appropriate location and reporting errors for each case.

**Comment by vsimonian** [comment]
What is the status/consensus on this PR?

**Comment by christiansmith** [comment]
I think we can close this one. I cherry picked the commit requiring modinha incorrectly. 

This PR came in while implementing support for custom providers/protocols (which still needs to be documented). The behavior was correct, but the incorrect require was causing an issue when we simply wanted to ignore the non-existent custom protocol.

**Pull request closed without merging**
