### PR TITLE
Implement SAML 2.0 protocol support

### PR DESCRIPTION
**Pull request by vsimonian**

### CODE REVIEW

**Comment by christiansmith** [comment]
https://github.com/anvilresearch/connect/issues/137

**Comment by vsimonian** [comment]
Whether or not we wait for https://github.com/bergie/passport-saml/pull/113 largely depends on whether or not multiple `AttributeStatement`s generally exist in SAML 2.0 responses for the majority of our users who intend to use SAML.

**Comment by christiansmith** [comment]
@vsimonian I think we should probably go ahead and merge this and release, then update when the passport-saml update is released. But first, I want to shake it down with my local setup. Mind doing a walkthrough on the setup + code review? I can make time later today or some time tomorrow.

**Comment by christiansmith** [comment]
@vsimonian can you explain what `providerInfo`, `providerNames`, and `visibileProviders` is all about?

https://github.com/anvilresearch/connect/pull/245/files#diff-6d4018922cfaa7ff5385670907dccb09R18

**Comment by christiansmith** [comment]
Also, are you able to resolve the conflicts on your end? Now that https://github.com/bergie/passport-saml/pull/113 is merged, I want go ahead and merge/release this...

**Comment by vsimonian** [comment]
`providerInfo`, `providerNames`, and `visibleProviders` are different locals expected by the sign-in view, that were missing from this code, thus breaking the sign-in view rendering when it went down this code path. [Elsewhere, they already exist.](https://github.com/anvilresearch/connect/blob/28375d01f74adddafbb74380e4c7c8cde5d0b78f/routes/signin.js#L18) `providerInfo` is the provider definition information keyed by provider ID, `providerNames` is a list of provider IDs, and `visibleProviders` contains only providers not marked as hidden.

Hopefully conflicts should be resolved by now.

**Comment by christiansmith** [comment]
@vsimonian good catch on the missing state. What's the purpose of hidden providers? This must be something you added when working on LDAP/AD, etc? I don't recall writing that code...

**Comment by vsimonian** [comment]
Hidden providers was implemented for the CLI, allowing the password provider to be always enabled but not visible to allow authority users to continue to sign in for server administration.

**Comment by christiansmith** [comment]
Know of a SAML service that's easy to integrate with for testing before I merge?

**Comment by vsimonian** [comment]
http://stubidp.kentor.se should be the easiest to work with; you have complete control over the entire set of SAML claims that gets returned.

**Comment by christiansmith** [comment]
@vsimonian mind writing up documentation for using this in a PR on connect-docs?

**Comment by christiansmith** [comment]
Verified. Still needs docs.

**Pull request merged**
