### PR TITLE
Passwordless or Email only login

### PR DESCRIPTION
**Pull request by henrjk**
This is related to issue #124.

### CODE REVIEW

**Comment by christiansmith** [comment]
Let's plan on a code review at the hangout on Thursday.

**Comment by henrjk** [comment]
## Known Issues ##

### AMR for passwordless?

Currently 'email' is used as AMR for passwordless. However this is not in the standard doc at https://tools.ietf.org/html/draft-jones-oauth-amr-values-01#section-2 .

Needs to be clarified how to handle this?

### interrupted flow in popup with angular client 

In password authentication the authorization happens in response to a redirect when the password is submitted.
This allows the popup when the callback is displayed to
1. send a message to the opener window
2. close itself

However this does not work when an outside email link is activated which results in a poor user experience. At the moment it is unclear to me how to best resolve this.

## Noteworthy observations ##

1. The code is not using passport. 

2. It does not plug-in to the provider architecture. It should be reviewed whether this is somehow wrong.

3. Most code handling passwordless is in file [routes/passwordless.js](https://github.com/henrjk/connect/blob/pwless/routes/passwordless.js). Most passwordless middleware seems not to be a candidate for sharing. This is my motivation to keep the passwordless specific middleware outside of the oidc folder.  
The main integration is done with routes/signin.js. In addition the passwordless middleware may render the 'signin' view to display errors when the email is invalid for example. To allow showing the signin page with the configured visible providers this code was moved to render/renderSignin.js. 

4. New shareable middleware is `oidc/verifyEmailValid.js`
and `oidc/veriftMailerConfigured.js`. Is usage outside of passwordless code has not yet been coded, but should be done in case this PR will ultimately be merged.

## Testing ##

-  There are new tests related to passwordless in `test/integration/routes` and in `test/unit/oidc/passwordless*.coffee` The coverage with these is quite high. My shippable build reports 92.19% branch coverage and 99.26% sequence coverage.

- I made some changes for unit testing in particular so that the settings middleware does not read and lock-in cached settings during setup but instead when requests come in. This simplified having tests with specific settings in place.  The coffee [class TestSetting](https://github.com/henrjk/connect/blob/pwless/test/lib/testSettings.coffee) helps setting up and restoring  these settings.

- proxyquire a new dev dependency was used for a test related to [settings](https://github.com/henrjk/connect/blob/pwless/test/unit/boot/settings.coffee). This could probably be avoided if the settings initialization would be more *injectible* whatever that shall mean.

**Comment by henrjk** [comment]
OK absolutely. I note this in my calendar. Let me know if the agenda changes. If you see anything problematic please let me know right away.

- Henrich

**Comment by henrjk** [comment]
I also made a tweak in https://github.com/anvilresearch/connect-example-angularjs. 
Among these is that session.userInfo.name was no longer populated. 
So at [line 18 of index.html](https://github.com/anvilresearch/connect-example-angularjs/blob/952b123d752a1a379676727cfdf664b3d8211754/app/index.html#L18) I changed this for the moment to 

```
<li ng-show='session.userInfo'><a ng-href='#'>{{session.userInfo.name || session.userInfo.given_name || session.userInfo.email}} </a></li>
```

However I was wondering whether the name should be computed somehow from the given_name and family_name. 

Some of the other changes are related to registering the client but also the code. 

In my branch there I also ripped out a bunch of validation as I am not a believer of heavy crypto in the browser. 

I will have to invest a few more cycles before I can share this so that the non validation would be optional. Or perhaps I keep this private to myself. I will do more work in the example early next week.

**Comment by vsimonian** [comment]
This PR is extremely broad in scope. Is there any reason that _all_ of these changes are necessary to implement passwordless/e-mail only sign-in?

**Comment by henrjk** [comment]
I hope the following helps to make this more digestible. The commits reflect the entire history how the code came and has not be cleaned. 

Unfortunately the majority of change is needed for to the passwordless feature or its testing. But you will find a few things below mentioned that could be removed or undone. 
Some changes which appear to be not strictly required were done to simplify testing in particular the new integration tests. 

The non test JavaScript code is mostly in routes/passwordless.js which is 450 lines. This and its integration with the signin are at the heart of this PR.  

The vast majority of changes is in test, here is an overview comparing `wc -l` between master and pwless:

```
connect2 dev$ find . -name "*.js" | grep -v node_modules | grep -v vendor | xargs wc -l
```

type/branch        | master  | pwless |  delta
--------|--------:|-------:|------:
*.js:   |  11936  |  12555 |  619
*.jade: |    387  |    463 |   76
*.hogan:|     77  |    129 |   52
*.coffee:| 13045  |  15508 | 2463 

With hindsight one can breakdown the changes as follows:

* *'mailer API simplification'* commit a74e82a27 causes the changes in mailer and 5 files that have no other changes. This could potentially be removed or go into a separate PR. 

* *'.gitignore to ignore coverage'* this slipped in and should be removed.

* *'passwordless tests'* - 15 files added, package.json changed for proxyquire and also oidc/enforceReferrer.js change to ease changing settings after initialization to ease testability. This changes allow the new integration tests without them having to use proxyquire and not be depending on your current configuration.
commit 798650d0 (test/unit/boot/settings.coffee) is the one requiring proxyquire and asserts some things that has been used in other code.  One could debate the need for this test and remove it.

* *'passwordless implementation'* - adds 5 js files, 5 changed and 5 templates added.

* *'shared oidc verifyEmailValid verifyMailerConfigured and tests'* - 4 files added 1 file changed.
This code was extracted from the current mail verification code so that it could be shared. At the moment I have not actually made the changes to call them from mail verification to reduce the number of changes.  

## passwordless implementation

### Changes
- routes/signin.js: main integration changes are here.
- server.js: trivial change
- providers/index.js: enable overriding tokenTTL.
- models/OneTimeToken: one new code path when id is undefined.
- oidc/determineProvider: Support {options: requireProvider}
- shared oidc verifyEmailValid verifyMailerConfigured (see above)

## Additions js code
- routes/passwordless.js -- the main part of this PR.
- protocols/Passwordless.js  -- just a stub to allow other code to not change
- providers/passwordless.js -- similar to providers/password.js
- errors/PasswordlessDisabledError.js 
- render/renderSignin: New module to allow res.render('signin') call with proper context from passwordless code. Refactored from signin.js

**Comment by henrjk** [comment]
I am pretty close on having a branch with new commits (done with rebase -i) where there are now about 9 commits for the same code changes. The much reduced # of commit would make this quite a bit easier to approach.
However I am not entirely sure whether it is a good idea to update this PR with new (rewritten) commits.  Please let me know what you think. 

Also I am not certain on how to update this PR exactly.

**Comment by christiansmith** [comment]
Hopefully @vsimonian can provide some guidance here. He's got an unusually good handle on the dark corners of git.

**Comment by henrjk** [comment]
Found this one http://blog.adamspiers.org/2015/03/24/why-and-how-to-correctly-amend-github-pull-requests/ 
The author advocates that rewritten and force pushing is the way to go. However a commenter advocates for simply creating a new PR. What do you suggest?

**Comment by vsimonian** [comment]
I'm all for a new PR (and/or PRs), just for simplicity's sake.

**Comment by henrjk** [comment]
I am closing this one as there is the 2nd one still open.

**Pull request closed without merging**
